ALTER TABLE "User"
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "passwordHash" DROP NOT NULL,
ALTER COLUMN "passwordSalt" DROP NOT NULL;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "telegramId" TEXT,
ADD COLUMN IF NOT EXISTS "telegramUsername" TEXT,
ADD COLUMN IF NOT EXISTS "telegramFirstName" TEXT,
ADD COLUMN IF NOT EXISTS "telegramLastName" TEXT,
ADD COLUMN IF NOT EXISTS "telegramPhotoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "telegramAuthDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastTelegramAuthAt" TIMESTAMP(3);

CREATE UNIQUE INDEX IF NOT EXISTS "User_telegramId_key" ON "User"("telegramId");
